# Generated by Django 4.1.3 on 2022-12-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="post/"),
        ),
    ]
